### ISSUE TITLE
Find an interesting subject

### ISSUE THREAD

**Issue by MichaelPolla** [cimami/ge-crash#1]

**Comment by MichaelPolla** [comment]
Some ideas : 

1) **Database of food products**, that can be shown divided by ingredient. Like in the following picture, but with an histogram (each sector textured with the corresponding ingredient).
<img src="https://user-images.githubusercontent.com/10487171/31576005-daf6c900-b0f2-11e7-886d-f347287ff8da.png" width="200">
Goal : to show people what they are really eating.<br>

2) 1) I find this visualization amazing : [U.S. Gun Deaths visualization](http://guns.periscopic.com/?year=2013). We could try to do the same with other data, for example : various type of cancers or other diseases. Maybe we could also integrate some elements (treatments and the extended lifetime gained, or some causes - e.g. lung cancers by smoking/non-smoking people).

   2) People dying because of obesity-related problems, vs people dying from hunger.
   3) Create the a generic system, for which we can give the data we want.

3) Map of Geneva with trees most responsible of allergies, with variation over the time of the year.
Goal : to help people with allergies to avoid some places given a certain date.

**Comment by maximeburri** [comment]
Visualizing in real-time in Geneva car accidents like http://worldbirthsanddeaths.com/ or other data from SITG
